motd = "Welcome to duty guard, have a safe day"

[main_menu]
label = "main"

[[main_menu.buttons]]
label = "Work"
command = ""
menu = []
[[main_menu.buttons.0.menu]]
label = "Record"
command = "smng r 1"
menu = []
[[main_menu.buttons.0.menu]]
label = "Stop"
command = "smng s 'strip guard duty'"
menu = []
[[main_menu.buttons.0.menu]]
label = "Status"
command = "smng status"
menu = []

[[main_menu.buttons]]
label = "EMERGENCY"
command = "echo 'Dr House messaged, stay calm and hold your position!'"
menu = []